const LEX_CONTENTS = [
  "all adjective clusters",
  "relational adjectives (pertainyms)",
  "all adverbs",
  "unique beginner for nouns",
  "nouns denoting acts or actions",
  "nouns denoting animals",
  "nouns denoting man-made objects",
  "nouns denoting attributes of people and objects",
  "nouns denoting body parts",
  "nouns denoting cognitive processes and contents",
  "nouns denoting communicative processes and contents",
  "nouns denoting natural events",
  "nouns denoting feelings and emotions",
  "nouns denoting foods and drinks",
  "nouns denoting groupings of people or objects",
  "nouns denoting spatial position",
  "nouns denoting goals",
  "nouns denoting natural objects (not man-made)",
  "nouns denoting people",
  "nouns denoting natural phenomena",
  "nouns denoting plants",
  "nouns denoting possession and transfer of possession",
  "nouns denoting natural processes",
  "nouns denoting quantities and units of measure",
  "nouns denoting relations between people or things or ideas",
  "nouns denoting two and three dimensional shapes",
  "nouns denoting stable states of affairs",
  "nouns denoting substances",
  "nouns denoting time and temporal relations",
  "verbs of grooming, dressing and bodily care",
  "verbs of size, temperature change, intensifying, etc.",
  "verbs of thinking, judging, analyzing, doubting",
  "verbs of telling, asking, ordering, singing",
  "verbs of fighting, athletic activities",
  "verbs of eating and drinking",
  "verbs of touching, hitting, tying, digging",
  "verbs of sewing, baking, painting, performing",
  "verbs of feeling",
  "verbs of walking, flying, swimming",
  "verbs of seeing, hearing, feeling",
  "verbs of buying, selling, owning",
  "verbs of political and social activities and events",
  "verbs of being, having, spatial relations",
  "verbs of raining, snowing, thawing, thundering",
  "participial adjectives"
];
export default LEX_CONTENTS;
