const POINTER_NAME = new Map([
  ["&", "Similar to"],
  ["$", "Verb group"],
  ["^", "Also see"],
  ["!", "Antonym"],
  ["\\", "Pertainym"],
  ["=", "Attribute"],
  [">", "Cause"],
  ["*", "Entailment"],
  ["+", "Derivationally related form"],
  ["<", "Participle of verb"],
  ["@", "Class hypernym"],
  ["@i", "Instance hypernym"],
  ["~", "Class hyponym"],
  ["~i", "Instance hyponym"],
  ["#m", "Member holonym"],
  ["#s", "Substance holonym"],
  ["#p", "Part holonym"],
  ["%m", "Member meronym"],
  ["%s", "Substance meronym"],
  ["%p", "Part meronym"],
  [";c", "Domain of synset - TOPIC"],
  [";r", "Domain of synset - REGION"],
  [";u", "Domain of synset - USAGE"],
  ["-c", "Member of this domain - TOPIC"],
  ["-r", "Member of this domain - REGION"],
  ["-u", "Member of this domain - USAGE"]
]);
export default POINTER_NAME;
